### PR TITLE
Closes #3

### LINKED ISSUE #3: Add invalid state
Simply add a new property isInvalid to be passed to the Chakra Input component.

### PR DESCRIPTION
**Pull request by anubra266**
Add Invalid State to be passed down to Chakra Input

### CODE REVIEW

**Comment by Fedeorlandau** [comment]
@anubra266  thank you! Could you please update the README.md file ? At the bottom of that file I'm adding all the options

**Comment by anubra266** [comment]
It's done.

**Comment by anubra266** [comment]
Are there still any changes you'll like me to make in this PR

**Comment by Fedeorlandau** [comment]
@anubra266 I think you forgot to push your changes to the readme.md file. I only see 1 file changed

**Comment by anubra266** [comment]
Sorry, I did it on another branch. It's  corrected now

**Review by Fedeorlandau — APPROVED** [review]

**Comment by Fedeorlandau** [comment]
Thank you @anubra266 ! merged. I'll release it soon

**Pull request merged**
